# pytorch_lightning==2.0.2
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      name: clinic150_classifier
      project: ZOC_debug
  callbacks:
    - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: 'val_loss'
        patience: 10
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val_loss'
        save_top_k: 1
        mode: min
  fast_dev_run: false
  max_epochs: 2
  min_epochs: null
  max_steps: 100000000000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null

model:
  num_labels: 150
  model_path: bert-base-uncased
  lr: 1.0e-05
  checkpoint_path: checkpoints/clinic150_bert

data:
  class_path: text_classification.class_split_datamodule.ClassSplitDataModule
  init_args:

    train_dataset:
      class_path: text_classification.class_split_datamodule.ClassSplitWrapper
      init_args:
        class_split_seed: null
        seen_class_ratio: null
        ood_labels: []
        val_ratio: null
        val_split_seed: null
        mode: null
        dataset:
          class_path: text_classification.clinic150_datamodule.CLINIC150
          init_args:
            mode: train
            path: data/clinc150/
            tokenizer_path: 'bert-base-uncased'
            add_oos: false
            oos_only: false
            wiki_for_test: false
            beautify_intents: true

    val_dataset:
      class_path: text_classification.class_split_datamodule.ClassSplitWrapper
      init_args:
        class_split_seed: null
        seen_class_ratio: null
        ood_labels: []
        val_ratio: null
        val_split_seed: null
        mode: null
        dataset:
          class_path: text_classification.clinic150_datamodule.CLINIC150
          init_args:
            mode: train
            path: data/clinc150/
            tokenizer_path: 'bert-base-uncased'
            add_oos: false
            oos_only: false
            wiki_for_test: false
            beautify_intents: true

    test_dataset:
      class_path: text_classification.clinic150_datamodule.CLINIC150
      init_args:
        mode: val
        path: data/clinc150/
        tokenizer_path: 'bert-base-uncased'
        add_oos: false
        oos_only: false
        wiki_for_test: false
        beautify_intents: true

    class_split_seed: null
    seen_class_ratio: null
    ood_labels: []
    batch_size: 128
    val_ratio: 0.1
    val_split_seed: 42